jobs:
  build:
    docker:
    - image: circleci/ruby:2.4-node
    steps:
    - checkout
    - run: env
    - inline_test/hello_world
orbs:
  inline_test:
    commands:
      hello_world:
        steps:
        - nested_inline/check_bash_version
        - run: echo "hello world inline"
    orbs:
      nested_inline:
        commands:
          check_bash_version:
            steps:
            - run: bash --version
version: 2.1

